### ISSUE TITLE
Warning during installation

### ISSUE THREAD

**Issue by lukapaunovic** [serghey-rodin/vesta#1754]
```
  Installing : vesta-ioncube-0.9.8-23.x86_64                                                                                              289/301 
/usr/local/vesta/ioncube/ioncube.sh: line 19: /etc/init.d/vesta: No such file or directory
warning: %post(vesta-ioncube-0.9.8-23.x86_64) scriptlet failed, exit status 127
Non-fatal POSTIN scriptlet failure in rpm package vesta-ioncube-0.9.8-23.x86_64
```

Another what I noticed

```
Redirecting to /bin/systemctl start spamassassin.service
groupadd: GID '1001' already exists
useradd: group 'spamd' does not exist
mkdir: cannot create directory ‘/var/lib/spamassassin’: File exists
chown: invalid user: ‘spamd:spamd’

```

New warnings on fresh Centos 7.5

**Comment by pablobae** [comment]
Same here

**Comment by cmstew** [comment]
Commit #1800 should resolve the spamassassin errors reported in this issue.

**Comment by lukapaunovic** [comment]
This is still present in Cent OS 7.6
@dpeca  please verify @cmstew  commit and merge.
