### ISSUE TITLE
Memory on /list/services/ page not functioning as expected

### ISSUE THREAD

**Issue by dustindauncey** [serghey-rodin/vesta#188]
Hi there,

I am curious about the functionality and behaviour of the Services page. I notice everything appears fine except in my environment I notice the Memory is not what is currently used. To be honest, I'm not sure what it represent.

 I have a server on 512 MB of memory, yet I see 1799 mb on the Http line, for example. This does not make sense to me. And restarting the service only seems to increment the number. Is it not working or is it working to show the total usage since install? 

It appears to me that it should be showing the current memory usage, or at least that is what a user would expect, in my opinion.

**Comment by KuJoe** [comment]
I noticed this also, if I add up the total memory for all services it shows over 5GB of RAM used when my server only has 512MB. I checked the source code and when I run the commands manually that are used to calculate the memory, the result I get is much different than what is displayed in Vesta.

The displayed memory usage for Apache (httpd) is 4126MB, the result I get from running the commands manually is 733.355 (still more than my VPS has, but much closer to something realistic).

[root@web ~]# pidof -x httpd |tr ' ' '|'
16616|16615|16614|16613|16612|16611|16610|16609|16592|16581
[root@web ~]# tmp_file=$(mktemp)
[root@web ~]# ps -eo pid,pcpu,size > $tmp_file
[root@web ~]# echo $tmp_file
/tmp/tmp.MEkutrtQh7
[root@web ~]# egrep "16616|16615|16614|16613|16612|16611|16610|16609|16592|16581" /tmp/tmp.MEkutrtQh7
16581  0.0 82808
16592  0.0  2400
16609  0.0 83200
16610  0.0 83320
16611  0.0 83192
16612  0.0 83240
16613  0.0 83232
16614  0.0 83216
16615  0.0 83252
16616  0.0 83096
[root@web ~]# pids=$(egrep "16616|16615|16614|16613|16612|16611|16610|16609|16592|16581" /tmp/tmp.MEkutrtQh7)
[root@web ~]# echo "$pids" |awk '{sum += $3} END {print sum/1024 }'
733.355

**Comment by serghey-rodin** [comment]
Hi
This issue was fixed. Fix will be available in new version. For now you can just manually download new script and apply the patch.
```
wget https://raw.githubusercontent.com/serghey-rodin/vesta/master/bin/v-list-sys-services -O /usr/local/vesta/bin/v-list-sys-services
```

**Comment by vector-man** [comment]
@serghey-rodin I tried running that line you mentioned will fix the bug, but MySQL is still showing a huge ammount of RAM (more than my VPS has.)
