### ISSUE TITLE
New version 1.0 released???

### ISSUE THREAD

**Issue by sveneld** [serghey-rodin/vesta#2089]
Suddenly new version appear on my server.
What happens?
http://i.piccy.info/i9/2abe7bca20ea45b2a8c379187c09b85d/1635673146/62692/1446608/123.jpg

**Comment by mix5003** [comment]
yes it mew release. but for now do not click any save button it still unstable

**Comment by sveneld** [comment]
So may by it should be signed as beta?
And what's new in this release?

**Comment by mix5003** [comment]
i am not sure what news in this release.
only think i known is 1.0.0-2 has so much bug. so don't try to create / edit thing in this release

**Comment by anton-reutov** [comment]
all important bugs will be fixed today, now we are working on it

**Comment by andyg2** [comment]
Looks like the devs have been through the code with a bulldozer over the past week, then pushed out version 1 without much testing.

October 24, 2021 – October 31, 2021
Excluding merges, 3 authors have pushed 31 commits to master and 31 commits to all branches. On master, 734 files have changed and there have been 14,103 additions and 10,836 deletions.

Some bugs I've noticed:

I don't have Mail support installed but adding a domain will not let me uncheck mail support. Same for DNS support, I have to delete the checkbox.

TLS certificates are not working for new domains.

Cannot change proxy templates.

Responsive design menus not working.

**Comment by anton-reutov** [comment]
1. fixed
3. fixed

2, 4  write more please

**Comment by andyg2** [comment]
>     1. fixed 3. fixed
>     2, 4 write more please

TLS certificates are not working for new domains.

When I edit an existing domain name and check SSL Support and Let's Encrypt support > Save: The page instantly reloads with the Let's Encrypt support unchecked.
Top bar message reports:  `Editing Domain Changes have been saved`

There's not much in the logs for this except:

`2021/10/31 10:26:10 [error] 9142#0: *320 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/local/vesta/web/api/v1/login/index.php on line 129
PHP message: PHP Notice:  Undefined variable: error in /usr/local/vesta/web/api/v1/login/index.php on line 167" while reading response header from upstream, client: xx.xxx.xxx.xxx, server: _, request: "GET /api/v1/login/index.php?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx HTTP/1.1", upstream: "fastcgi://unix:/var/run/vesta-php.sock:", host: "xxx.xx.xx.xx:5600", referrer: "https://xxx.xx.xx.xx:5600/edit/web?domain=xxxxx.xxxxxxxxxxxxxx.xx.xx"`

**Here's the Request**
```
-----------------------------340899093313999683301027358632
Content-Disposition: form-data; name="save"

save
-----------------------------340899093313999683301027358632
Content-Disposition: form-data; name="token"

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
-----------------------------340899093313999683301027358632
Content-Disposition: form-data; name="v_domain"

xxxxx.xxxxxxxxxxxxxx.xx.xx
-----------------------------340899093313999683301027358632
Content-Disposition: form-data; name="v_ip"

xxx.xx.xx.xx
-----------------------------340899093313999683301027358632
Content-Disposition: form-data; name="v_aliases"


-----------------------------340899093313999683301027358632
Content-Disposition: form-data; name="v_template"

default
-----------------------------340899093313999683301027358632
Content-Disposition: form-data; name="v_proxy_template"

default
-----------------------------340899093313999683301027358632
Content-Disposition: form-data; name="v_proxy_ext"


-----------------------------340899093313999683301027358632
Content-Disposition: form-data; name="v_shared"

on
-----------------------------340899093313999683301027358632
Content-Disposition: form-data; name="v_letsencrypt"

on
-----------------------------340899093313999683301027358632
Content-Disposition: form-data; name="v_ssl_home"

public_html
-----------------------------340899093313999683301027358632
Content-Disposition: form-data; name="v_stats"

none
-----------------------------340899093313999683301027358632--
```



**And the response**
```
{
  "username": "xxxxxxx",
  "domain": "'xxxxx.xxxxxxxxxxxxxx.xx.xx",
  "ip": "xxx.xx.xx.xx",
  "template": "default",
  "aliases": "",
  "valiases": [""],
  "tpl": "xxx.xx.xx.xx",
  "elog": null,
  "ssl": "no",
  "cgi": null,
  "ssl_crt": "",
  "ssl_key": "",
  "ssl_ca": "",
  "ssl_subject": "",
  "ssl_aliases": "",
  "ssl_not_before": "",
  "ssl_not_after": "",
  "ssl_signature": "",
  "ssl_pub_key": "",
  "ssl_issuer": "",
  "letsencrypt": "yes",
  "ssl_home": "same",
  "backend_template": "",
  "proxy": "",
  "proxy_template": "",
  "proxy_ext": "",
  "v_stats": "",
  "stats_user": "",
  "ftp_user": null,
  "ftp_path": "",
  "ftp_password": null,
  "ftp_user_prepath": "\/xxxx\/xxxxx\/xxx\/xxxxx.xxxxxxxxxxxxxx.xx.xx",
  "ftp_email": null,
  "suspended": "no",
  "status": "active",
  "time": "08:56:57",
  "date": "2021-10-31",
  "ips": {
    "xxx.xx.xx.xx": {
      "OWNER": "admin",
      "STATUS": "shared",
      "NAME": "",
      "NAT": ""
    }
  },
  "prefixI18N": "Prefix xxxxx_ will be automaticaly added to username",
  "ftp_users": [{
      "is_new": 1,
      "v_ftp_user": "",
      "v_ftp_password": "",
      "v_ftp_path": "",
      "v_ftp_email": "",
      "v_ftp_pre_path": "\/home\/xxxxx\/web\/xxxxxxxxxxxxxx.xx.xx"
    }
  ],
  "templates": ["256m", "PHP-FPM-73", "PHP-FPM-74", "basedir", "default", "hosting", "phpcgi", "phpfcgid"],
  "backend_templates": null,
  "proxy_templates": ["caching", "default", "force-https", "hosting"],
  "stats": ["none", "webalizer", "awstats"],
  "proxy_system": "nginx",
  "web_backend": "",
  "web_system": "apache2",
  "error_msg": null,
  "ok_msg": "Changes have been saved."
}
```

The responsive issues (not so important) - on the edit domain page the mezssage bar floats oevr the top links, the tops links are not clickable either - see image.

![image](https://user-images.githubusercontent.com/1462766/139578997-fe3f908d-430d-42ce-a7da-9c309fc9241d.png)

**Comment by PUQ-sp-z-o-o** [comment]
Good afternoon. 
The API does not work in the new version.
Editing the mail user does not work correctly.
I have a white screen on the server->configure.

**Comment by anton-reutov** [comment]
**andyg2**, Responsive will be fixed, SSL already fixed and waiting release

**PUQ-sp-z-o-o**, can't reproduce, what OS on your server? It's fresh install or update ?

_Editing the mail user does not work correctly._

Write more

**Comment by PUQ-sp-z-o-o** [comment]
The installation is old.
Update for 1 tonight.
Debian 9.13.
Changing the user's language does not work.
![VC-email](https://user-images.githubusercontent.com/81689153/139580973-412f30a5-1635-4178-b491-22218bb09d59.png)

When editing a mail user, there are no USER fields.

**Comment by ninjao** [comment]
@anton-reutov 

Thanks for checking all of this. I am sure you guys are working on it fast. 

My problem is: 99% of _all my domains are currently offline_, **including the domain for my panel**. 

I can only access panel with direct ip:port address in browser. 

Will the fixes also fix this issue? It seems other people don't have an extreme case like mine where _almost everything_ is offline?

**Comment by anton-reutov** [comment]
**ninjao**, can you provide access to your server, we will check what happened with your sites.
You can send access credentials to info@vestacp.com

**Comment by PUQ-sp-z-o-o** [comment]
The API does not work.
DNS-Clastet error:
```
/usr/local/vesta/bin/v-sync-dns-cluster XXX.XXX.XX
/usr/local/vesta/func/remote.sh: linia 26: return: <!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/images/favicon.ico"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"/><meta name="theme-color" content="#000000"/><link rel="manifest" href="/manifest.json"/><title>Vesta</title><link href="/static/css/2.6c9f324a.chunk.css" rel="stylesheet"><link href="/static/css/main.fb673c59.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script><script>!function(e){function r(r){for(var n,l,a=r[0],c=r[1],p=r[2],i=0,s=[];i<a.length;i++)l=a[i],Object.prototype.hasOwnProperty.call(o,l)&&o[l]&&s.push(o[l][0]),o[l]=0;for(n in c)Object.prototype.hasOwnProperty.call(c,n)&&(e[n]=c[n]);for(f&&f(r);s.length;)s.shift()();return u.push.apply(u,p||[]),t()}function t(){for(var e,r=0;r<u.length;r++){for(var t=u[r],n=!0,a=1;a<t.length;a++){var c=t[a];0!==o[c]&&(n=!1)}n&&(u.splice(r--,1),e=l(l.s=t[0]))}return e}var n={},o={1:0},u=[];function l(r){if(n[r])return n[r].exports;var t=n[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,l),t.l=!0,t.exports}l.m=e,l.c=n,l.d=function(e,r,t){l.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},l.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},l.t=function(e,r){if(1&r&&(e=l(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(l.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var n in e)l.d(t,n,function(r){return e[r]}.bind(null,n));return t},l.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return l.d(r,"a",r),r},l.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},l.p="/";var a=this["webpackJsonpreact-control-panel"]=this["webpackJsonpreact-control-panel"]||[],c=a.push.bind(a);a.push=r,a=a.slice();for(var p=0;p<a.length;p++)r(a[p]);var f=c;t()}([])</script><script src="/static/js/2.d2b0a6c3.chunk.js"></script><script src="/static/js/main.96e25cf6.chunk.js"></script></body></html>: wymagany argument numeryczny
Error: XXX.XXX.XX connection failed
```

**Comment by anton-reutov** [comment]
**PUQ-sp-z-o-o** email users - **confirmed**

**Comment by anton-reutov** [comment]
> I have a white screen on the server->configure.
**PUQ-sp-z-o-o** can't reproduce.

**Comment by PUQ-sp-z-o-o** [comment]
> > У меня на сервере белый экран-> настроить.
> 
> **PUQ-sp-zoo** не может воспроизвести.
I will clarify.
Only on servers on which the dns cluster is configured.

**Comment by PUQ-sp-z-o-o** [comment]
> > I have a white screen on the server->configure.
> 
> **PUQ-sp-z-o-o** can't reproduce.

I will clarify.
Only on servers on which the dns cluster is configured.

**Comment by skorpions2000** [comment]
How can we do rollback to previous version vestacp? so many no working... on updated version our favorite control panel

**Comment by anton-reutov** [comment]
> 
> 
> Good afternoon. The API does not work in the new version. Editing the mail user does not work correctly. I have a white screen on the server->configure.

fixed, waiting release

**Comment by AyhanDelican** [comment]
Debian ssl problem still persists.
In the past, it did not give an error and did not create ssl.

now it just gives an error and it doesn't create the SSL certificate.
Error: Let's Encrypt validation status 400

When is this expected to be fixed? All our work is delayed. 
Thanks Vesta Team.
We always run the tests together, it's like Microsoft Windows.

**Comment by anton-reutov** [comment]
What Vesta Core version on your server ?

**Comment by AyhanDelican** [comment]
> 
> 
> What Vesta Core version on your server ?

core package
Version: 1.0.0 (amd64)
Release: 3

![Image1](https://user-images.githubusercontent.com/23042390/139664361-aca64369-6420-4ea2-b021-cee748c4a15c.png)

**Comment by anton-reutov** [comment]
can your provide screenshot list of webdomains ?
you can send a screenshot to info@vestacp.com

**Comment by AyhanDelican** [comment]
> can your provide screenshot list of webdomains ?

I sent the mail as you requested.

**Comment by anton-reutov** [comment]
Enable proxy support fro your domain and try generate LE again

**Comment by AyhanDelican** [comment]
OK, it worked.
Thanks.

**Comment by sveneld** [comment]
https://example.com:8083/list/web-log/?domain=example.com&type=access
https://example.com:8083/list/web-log/?domain=example.com&type=error

shows only one row from log.
