### ISSUE TITLE
Bad configuration parsing/replacement of nginx.conf and snginx.conf

### ISSUE THREAD

**Issue by MrGreenStuff** [serghey-rodin/vesta#719]
Since last update (change in the domain.sh here : https://github.com/serghey-rodin/vesta/commit/872cd3ac453d0ec67df0e6971e693fba9a9bf679#diff-c481780ec662b2e934ad7fccc179b3ddR255 ) when i change the Template Web (On NGINX config) the replacement does not work correctly and the file nginx.conf and sningx.conf of the user became invalid or i have a "Error : can't parse config nginx.conf" and i have to edit the file manually (and the config generator make the config of the old template not the template actually selected when i save my domain).

Why do you use a difficult replacement method (here : https://github.com/serghey-rodin/vesta/blob/859798cb34c5a337b74c1e7509609736ce1148e3/func/domain.sh#L261 ) ? It's easier to create one file by domain and include it in /etc/nginx/vesta.conf or in the domain (s)nginx.conf with this method no difficult replacement just rewrite all the content of the domain file.

**Comment by Flatta** [comment]
+1 
The same thing happens with apache2.conf and sapache2.conf when I edit Aliases and Web Template at once.

![apache2.conf](https://cloud.githubusercontent.com/assets/11276413/16490207/9e103208-3f13-11e6-8099-6f9d75966906.png)
(Create a new web, delete all aliases and change web template to phpfcgid, and this happens)

**Comment by serghey-rodin** [comment]
This issue is already fixed. However fix wasn't included in early 16 release. You can run following commands to get the latest code
```
# RHEL/CentOS
yum clean all 
yum reinstall vesta

#Debian/Ubuntu
apt-get update
apt-get install --reinstall vesta
```

**Comment by MrGreenStuff** [comment]
It's still doesn't work after reinstallation
Here the content of my custom template tpl (it's just a redirection on the SSL version)

`server {
    listen      51.254.162.142:80;
    server_name test.XXXXX.fr ;
    return 301 https://$server_name$request_uri;
}`

And here the nginx.conf generated after changing default to mycustomtemplate

`   access_log  /var/log/nginx/domains/test.XXXXX.fr.log combined;
    access_log  /var/log/nginx/domains/test.XXXXX.fr.bytes bytes;
    error_log   /var/log/nginx/domains/test.XXXXX.fr.error.log error;

    location / {

        location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|css|js)$ {
            expires     max;
        }

        location ~ [^/]\.php(/|$) {
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            if (!-f $document_root$fastcgi_script_name) {
                return  404;
            }

            fastcgi_pass    127.0.0.1:9026;
            fastcgi_index   index.php;
            include         /etc/nginx/fastcgi_params;
        }
    }

    error_page  403 /error/404.html;
    error_page  404 /error/404.html;
    error_page  500 502 503 504 /error/50x.html;

    location /error/ {
        alias   /home/test/web/test.XXXXX.fr/document_errors/;
    }

    location ~* "/\.(htaccess|htpasswd)$" {
        deny    all;
        return  404;
    }

#    include     /etc/nginx/conf.d/phpmyadmin.inc*;
#    include     /etc/nginx/conf.d/phppgadmin.inc*;
#    include     /etc/nginx/conf.d/webmail.inc*;

    include     /home/test/conf/web/nginx.test.XXXXX.fr.conf*;
}
server {
    listen      51.254.162.142:80;
    server_name test.XXXXX.fr ;
    return 301 https://$server_name$request_uri;
}
`

So the replacement still doesn't work correctly and i still don't understand why do you use this complicated method.

**Comment by adthonb** [comment]
Same here. even use force-https from their official, so got issue.

**Comment by serghey-rodin** [comment]
I'm checking this and will keep you updated.

@MrGreenStuff  yes it is easier to create one file by domain.  However there was good reason for making one config per user. Now even if we want to change default behaviour it is not that simple because there are a lot of server that are using old scheme. Anyway it was perfectly working before and I should fix it without changing architecture

**Comment by serghey-rodin** [comment]
I don't understand how to reproduce this bug. Maybe some of you guys @MrGreenStuff @Flatta @adthonb can provide me with temporary access on the server where it is reproducible?
Please email me skid at vestacp dot com thanks

**Comment by adthonb** [comment]
@serghey-rodin I sent information to your email. Please check, sir. Thanks
