### ISSUE TITLE
Rebuild Web Deletes nginx.conf & snginx.conf

### ISSUE THREAD

**Issue by razzbee** [serghey-rodin/vesta#721]
Hello , I just updated vesta cp to the latest but the is a serious bug , I rebuilt an account , the nginx.conf and snginx.conf in that account conf web folder got deleted and was not recreated , I dont know why

**Comment by serghey-rodin** [comment]
Yes this is known bug and we fixed it few hours ago.
In order to rebuild web configuration properly please use cli.
`v-rebuild-web-domains $username`

**Comment by xguntis** [comment]
this is closed on Jun 30. Now it is Oct 26 and the problem is still there? I use 	
Version:0.9.8 (amd64)	
Release:16

**Comment by dpeca** [comment]
Run:
```
cd /root
git clone https://github.com/serghey-rodin/vesta.git
cp -rf /root/vesta/* /usr/local/vesta
```

Then check bug again.

**Comment by xguntis** [comment]
is it safe to run unreleased version? And what if i have enabled Autoupdate? Should i disable it if running latest commit?

**Comment by dpeca** [comment]
I use git version on production servers - but however - I wlll NOT suggest you to do that.
I thought you can check existence of this bug on some virtual machine, for example.
